export default {
  primary: '#9634ff',
  secondary: '#0D2045',
  background: '#f3f2f8',
  screenBackgroundColor:'#ffffff',
  white: '#fff',
  dropDown: '#4B8FC8',
  headerBackgroundColor: '#F6AC15',
  alertDialogHeaderBackgroundColor: '#7399AE',
  headerTitleColor: '#FFFFFF',
  textInputBorderColor: '#7868e6',
  textInputTextColor: 'black',
  buttonBackgroundColor: '#FF8000',
  buttonTextColor: '#FFFFFF',
  phraseBorderColor:'lightgrey',
  phraseNumberColor:'grey',
  phraseTextColor:'black',
  searchPlaceHolderText:'#787878',
};
